//
// Created by Shant Zargarian on 4/2/23.
//

#ifndef CS3A_SPRING23_SFMLCARD_SCORES_H
#define CS3A_SPRING23_SFMLCARD_SCORES_H


enum class Scores {
    ROYAL_FLUSH,
    STRAIGHT_FLUSH,
    FOUR_OF_A_KIND,
    FULL_HOUSE,
    FLUSH,
    STRAIGHT,
    THREE_OK_A_KIND,
    TWO_PAIR,
    ONE_PAIR,
    HIGH_CARD
};


#endif //CS3A_SPRING23_SFMLCARD_SCORES_H
